
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // This block overrides the schema's datasource for the migration engine.
    url: env("DATABASE_URL"),
    // Neon hands out a pooled and an unpooled URL; migrations need the
    // unpooled one. Locally there is no pooler, so both vars hold the same
    // value — but the schema declares directUrl, so it must always be set.
    directUrl: env("DIRECT_DATABASE_URL"),
  },
});
